name: Deploy Azure Bicep
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    
    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v4

      - name: Azure Login
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          

      # Determine which parameter file to use
      - name: Set environment variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "PARAMS_FILE=main.prod.bicepparam" >> $GITHUB_ENV
            echo "RESOURCE_GROUP=rg-myapp-prod" >> $GITHUB_ENV
          else
            echo "PARAMS_FILE=main.dev.bicepparam" >> $GITHUB_ENV
            echo "RESOURCE_GROUP=rg-myapp-dev" >> $GITHUB_ENV
          fi


      - name: Deploy Bicep
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: ./main.bicep
          parameters: ./${{ env.PARAMS_FILE }}

      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '22'

      # # 4️⃣ Install Angular dependencies
      # - name: Install npm dependencies
      #   run: npm ci

      # # 5️⃣ Build Angular app
      # - name: Build Angular
      #   run: | 
      #     npm run build -- --configuration production

      # # 6️⃣ Build Docker image
      # - name: Build Docker image
      #   run: |
      #     docker build -t reactwebapp .

      # # 7️⃣ (Otional) Push Docker image to Azure Container Registry
      # - name: Push Docker image to ACR
      #   run: |
      #     az acr login --name ${{ secrets.ACR_NAME }}
      #     docker tag reactwebapp ${{ secrets.ACR_NAME }}.azurecr.io/reactwebapp:latest
      #     docker push ${{ secrets.ACR_NAME }}.azurecr.io/reactwebapp:latest


      # # 8️⃣ (Optional) Deploy to Azure App Service
      # - name: Deploy to Azure App Service
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: ${{ secrets.APP_SERVICE_NAME }}
      #     images: ${{ secrets.ACR_NAME }}.azurecr.io/reactwebapp:latest
    